### ISSUE TITLE
Missing include GL with OCPN 5.2 on OpenSUSE with GTK3

### ISSUE THREAD

**Issue by dominig** [seandepagnier/climatology_pi#72]
As with the main code of OCPN 5.2,  ClimatologyOverlayFactory.cpp will not compile on OpenSUSE with the following error
'glXGetProcAddress' was not declared in this scope

As withing OCPN main code, th error is due to a miss configuration of GL include files when GTK3 is used.
see https://github.com/OpenCPN/OpenCPN/issues/1494

I have created the following patch which works for me, but might not be general enough to be up-streamed. At least it gives a hint of the issue. See my patch bellow.

Regards Dominig
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1c88c47..9211282 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -18,7 +18,7 @@ SET(CPACK_PACKAGE_CONTACT "Sean D'Epagnier ")
 SET(CMAKE_MACOSX_RPATH "ON")
 
 SET(CMAKE_CXX_STANDARD 11)
-
+INCLUDE("cmake/FindGTK3.cmake")
 INCLUDE("cmake/PluginConfigure.cmake")
 
 SET(SRC_CLIMATOLOGY
diff --git a/cmake/PluginConfigure.cmake b/cmake/PluginConfigure.cmake
index 82968a8..f481732 100644
--- a/cmake/PluginConfigure.cmake
+++ b/cmake/PluginConfigure.cmake
@@ -183,8 +183,8 @@ IF(OPENGL_GLU_FOUND)
     INCLUDE_DIRECTORIES(${OPENGL_INCLUDE_DIR})
 
     MESSAGE (STATUS "Found OpenGL..." )
-    #MESSAGE (STATUS "    Lib: " ${OPENGL_LIBRARIES})
-    #MESSAGE (STATUS "    Include: " ${OPENGL_INCLUDE_DIR})
+    MESSAGE (STATUS "    Lib: " ${OPENGL_LIBRARIES})
+    MESSAGE (STATUS "    Include: " ${OPENGL_INCLUDE_DIR})
     ADD_DEFINITIONS(-DocpnUSE_GL)
 ELSE(OPENGL_GLU_FOUND)
     MESSAGE (STATUS "OpenGL not found..." )
diff --git a/src/ClimatologyOverlayFactory.cpp b/src/ClimatologyOverlayFactory.cpp
index ebbe96e..829e67a 100644
--- a/src/ClimatologyOverlayFactory.cpp
+++ b/src/ClimatologyOverlayFactory.cpp
@@ -42,6 +42,11 @@
 #include "GLES2/gl2.h"
 #endif
 
+/* GTK3 GL include bug */
+#if defined(__WXGTK__)
+#include <GL/glx.h>
+#endif
+
 #include "climatology_pi.h"
 #include "gldefs.h"
 #include "icons.h"
```

**Comment by rgleason** [comment]
Thank you dominig. We will look at this when we have more skilled programming resources available.

**Comment by dominig** [comment]
Detail, my patch requires the presence of a file copied from OCPN main body to detect GTK3
https://github.com/OpenCPN/OpenCPN/blob/master/cmake/FindGTK3.cmake

**Comment by rgleason** [comment]
Doming, 
We've updated Climatology with the help of Jon and Bdbcat, and Sean has merged the PR on Sept 12 
See https://github.com/seandepagnier/climatology_pi 
You can see the full set of builds going to CirclecCi here
https://github.com/rgleason/climatology_pi

I believe this should fix the problem, but if it does not please let us know.
The Cloudsmith Repository for the current version 1.4.15.0 is here 
https://cloudsmith.io/~opencpn/repos/climatology-prod/packages/

Perhaps this can be closed now?

**Comment by dominig** [comment]
Sorry but that does not fix the issue with GTK3.
see my build log bellow.
Domnig
---------------------------------------
[   22s] -- Some or all of the gtk libraries were not found. (missing: GTK2_GTK_LIBRARY GTK2_GTK_INCLUDE_DIR GTK2_GDK_INCLUDE_DIR GTK2_GDKCONFIG_INCLUDE_DIR GTK2_GDK_LIBRARY) 
[   22s] CMake Warning at cmake/PluginConfigure.cmake:407 (find_package):
[   22s]   By not providing "FindGTK3.cmake" in CMAKE_MODULE_PATH this project has
[   22s]   asked CMake to find a package configuration file provided by "GTK3", but
[   22s]   CMake did not find one.
[   22s] 
[   22s]   Could not find a package configuration file provided by "GTK3" with any of
[   22s]   the following names:
[   22s] 
[   22s]     GTK3Config.cmake
[   22s]     gtk3-config.cmake

**Comment by rgleason** [comment]
Thank you Dominig for your patience with me. We will try to get this fixed.

**Comment by rgleason** [comment]
@jongough 
@dominig

Jon,, is there something else we can do for dominig's  OpenSuse case?

@dominig
I don't know why the  "opencpn" packaged deb files already in the repository that are using gtk3 don't work, particularly for gtk3 environments!

**Comment by jongough** [comment]
On what platform and platform version are you building on? If you build it in the cloud (circleci) does it work? Did it work OK with GTK2? If so there may be some work to do due to the differences between GTK2 & GTK3.

**Comment by rgleason** [comment]
Jon, I have updated Climatology to 1.0.143, but android and flatpak is not buiilding
https://github.com/rgleason/climatology_pi/commits/master

**Comment by dominig** [comment]
I am building with the official tool from OpenSUSE (OBS) and Fedora (Koji) [for an internal project not yet published].
The main advantage of using those tools is that, each time that the reused lib changes (eg wx) the distro check that the resulting packages are changed at binary level and take in charge the automatic distribution of the changes as partial rpm (or full depending of the size). The installation on target system s done automatically.
Those tools are great for maintaining thousandth of packages that enter in a distro but impose some constrains not running in a git tree is one of them.

**Comment by rgleason** [comment]
Dominig, can this be closed now?
